DROP DATABASE IF EXISTS foods;

CREATE DATABASE IF NOT EXISTS foods;

USE foods;

CREATE TABLE IF NOT EXISTS food (
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);